### ISSUE TITLE
Change Subtitle Size

### ISSUE THREAD

**Issue by HorselessName** [sheodox/jimaku-player#14]
Is it possible to resize the subtitle?
I have a ultra wide monitor and the subtitles on the site are too small. I would like to resize and make it bigger...
Is that possible?

**Comment by sheodox** [comment]
Not yet, but I could certainly add a feature like that that lets you adjust a font size scale! It wouldn't be too difficult. I'll put it on my todo list, I should have time this week to work on it!

I'm thinking a slider that lets you adjust the font size from like 25% to 300%. What do you think about that?

Also, out of curiosity, what kind of subtitles are they? WebVTT (it'll either have a `.vtt` extension or sometimes `.srt`, you can tell if it's WebVTT because it'll say `WEBVTT` as the first line of the file) and ASS format subtitles (`.ass` extension) can both specify the font size. Jimaku Player will try and scale it to the video player's height, but I've definitely seen some subtitles that have a really small font size and it's kind of a pain to see them.

Because the font sizes can vary by who made the subs (and you're likely to have a subtitles from the same source for other episodes of the same show) I might make the font size configurable by show, or maybe as an additional option. Like a global font size multiplier and a per-show override. Thoughts?

**Comment by sheodox** [comment]
@HorselessName I just released a new version (0.4.1) with the option to configure the font size. Here's the release notes:

> Got some cool new features here!
> * There's a new Subtitle font size scale setting which lets you make the subtitle between 50% and 300% of the size the subtitles are supposed to be. If your subtitles are too small you can use this option to make them the right size. Additionally if you use VRV you can also set a specific override for a show if only one show needs the sizes changed for one show in particular so you won't have to keep adjusting the font size when switching shows.
> * You can now choose which what happens when you click on a subtitle (in the tray or over the video). In addition to the existing Jisho search option, you can have it copy the text to your clipboard, or just do nothing.
> 

![image](https://user-images.githubusercontent.com/3468630/105243023-16919a00-5b34-11eb-98e1-e45bdd624769.png)

**Comment by HorselessName** [comment]
Awesome.

Em qua, 20 de jan de 2021 18:29, sheodox <notifications@github.com>
escreveu:
