### ISSUE TITLE
Sub position

### ISSUE THREAD

**Issue by spookyjj** [sheodox/jimaku-player#15]
Was wondering if there was a way to change the location of the subs to be centered/drag to position. Some subs I was using were automatically aligned with the corner of the screen. I downloaded different subs for the same show which were automatically centered, so it was just those specific subs that were aligned that way. Just a suggestion though, I like your script it's very helpful (don't have to download all eps of one piece now)

**Comment by sheodox** [comment]
Currently there isn't a way to do that. I think the dragging thing would be pretty complicated since different subtitles can have different positioning and there are a lot of factors.

But I've had an idea for a while for a feature for a setting that makes it ignore all styling in the subtitles and just render them with some reasonable defaults (basically the way plain `srt` files render, since the subrip format doesn't support styling as it's only text with start/end times - though sometimes you'll find WebVTT subtitles with a `.srt` file extension which do support styling). For the most part I think it'd be fine, though it'd look weird if the subtitles are split between the top/bottom of the screen when two conversations are going on and people are talking over each other.

What do you think of that? 

Glad you like the script! It's funny you mention One Piece, because it's the reason I made this in the first place, and a lot of the alignment related options are because the last ~600 episodes I've watched have had weird timing.

What kind of subtitles were you using for that one episode? If you have it could you attach them here? If it's a `.ass` file I'm fairly certain they were rendered correctly (unless they were meant to be written vertically, I don't support that yet) but if it's WebVTT (it'll either have a `.vtt` extension or the first line in the file will be `WEBVTT`) I might have a bug somewhere, I've not spent a ton of time on the more complex things WebVTT can do so maybe I messed something up!
