### ISSUE TITLE
Support for any website

### ISSUE THREAD

**Issue by pixelparker** [sheodox/jimaku-player#31]
Hey man, I was wondering if you could adapt this script to be used with any website that has an html5 player in it, instead of being tied to a specific platform. Cheers

**Comment by sheodox** [comment]
I don't think it could be easily done super generally very easily, the way elements like the settings tray are styled if a website had a different structure to their video player there'd probably be overlapping.

I think the bigger issue would be privacy concerns though. The script currently only runs on two very specific page URLs, in order to make it run on any html5 video player it'd need to have access to run on every site you go to. I know I'm not going to do anything malicious with that, but that's a lot of trust that people would be giving to some random guy on the internet!

I appreciate the ideas though!
