### ISSUE TITLE
Subtitles don't scale

### ISSUE THREAD

**Issue by SolarHusky** [sheodox/jimaku-player#33]
Watching Angel Beats Episode 1 with "Angel Beats! 01 (BD 720p)(Hi10).ja.ass" results in very small subtitles. Overriding subtitle scaling has no effect. 
![image](https://user-images.githubusercontent.com/54920518/134786102-bcae822b-1e9b-4779-9056-6960145c8633.png)

**Comment by sheodox** [comment]
Hey @SolarHusky, thanks for the report! This should be fixed now with version `0.5.6`! You can manually force an update by clicking "Check for Userscript updates"  in Tampermonkey's menu

![image](https://user-images.githubusercontent.com/3468630/134787203-046c6101-fa6a-4ac0-b2ae-b1ba80aa9036.png)

The cause of the issue was the subtitle script not including video resolutions which I use to scale font sizes to the size of your window (so when viewing in full screen the text will be bigger for example), causing all the math to result in unusable numbers (`NaN`, "not a number" in JS), which means it just showed the subtitle as the default font size for the page and since you can't do math with NaN, none of the scaling calculations did anything different.

I fixed it by setting a default video resolution of 1280x720 to do calculations on if none was found in the subtitles. Not sure if it's going to be exactly the right size, but you can adjust the size with that font scaling setting now!

**Comment by SolarHusky** [comment]
Wow, thanks. This did fix the problem. Fix came so fast I assumed my bug
was being closed as not a problem!

**Comment by sheodox** [comment]
Haha I didn't realize writing `Closes #33` in the commit message would actually automatically close the issue, took me a few minutes to write up that comment afterwards lol. Glad it fixed the problem!
